"""empty message

Revision ID: fd6e6d8bc8e6
Revises: fe07ca81f1d8
Create Date: 2024-10-19 16:25:10.164808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd6e6d8bc8e6'
down_revision: Union[str, None] = 'fe07ca81f1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
