site_name: Документация Web Development Tools
theme: readthedocs
repo_url: https://github.com/kdflr/ITMO_ICT_WebDevelopment_tools_2023-2024
nav:
  - Home: index.md
  - Lab 1: lab1.md
  - Lab 2: lab2.md
  - Lab 3: lab3.md