services:
  web:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: webapp_test
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /app/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./application:/app

  parser:
    build:
      context: .
      dockerfile: parser.Dockerfile
    container_name: parser_test
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./parser:/parser
      
  db:
    image: postgres
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hackathon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: